name: Test .NET CLI on Linux

on:
  workflow_dispatch:  # This allows you to run the workflow manually from the Actions tab

jobs:
  test-ubuntu-latest-release:
    runs-on: ubuntu-latest  # Uses the latest Windows environment

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install 7-Zip
        run: sudo apt update && sudo apt install -y p7zip-full
        
      - name: Extract Release Archive
        run: |
          7z x '!release\latest-unstable\LatestCli.7z' -o'release_extracted'  # Extract to 'release_extracted' folder

      - name: List Extracted Files
        run: dir release_extracted  # List files in the directory to confirm the .exe is present

      - name: Run CLI App Help Command
        shell: cmd # Explicitly set to CMD
        run: |
          release_extracted\DescribeTranspiler.CLI.exe -help auto
