name: Test .NET CLI on Windows Latest

on:
  workflow_dispatch:  # This allows you to run the workflow manually from the Actions tab

jobs:
  test-latest-release:
    runs-on: windows-latest  # Uses the latest Windows environment (Windows 11 equivalent)

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Use your .NET version

      - name: Install 7-Zip
        run: |
          choco install -y 7zip  # Install 7-Zip to extract .7z files

      - name: Extract Release Archive
        run: |
          7z x '!release\1.0-beta\DescribeCompiler.CLI.v1.0-beta.7z' -o'release_extracted'  # Extract to 'release_extracted' folder

      - name: List Extracted Files
        run: |
          dir release_extracted\DescribeCompiler.CLI.v1.0-beta  # List files in the directory to confirm the .exe is present
      
      - name: Run CLI App Help Command
        shell: pwsh  # Use PowerShell
        run: |
          & "release_extracted\DescribeCompiler.CLI.v1.0-beta\DescribeTranspiler.CLI.exe" -help *>&1 | Out-File output.txt # Redirect output to a file

      - name: List Extracted Files
        run: |
          dir release_extracted\DescribeCompiler.CLI.v1.0-beta  # List files in the directory to confirm the .exe is present
      
      - name: Get CLI App result 
        shell: pwsh  # Use PowerShell
        run: |
          Get-Content output.txt
    
